import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'

import { ChatEngine } from 'react-chat-engine';
import styles from '../styles/utils.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.chatPage}>
        

      <ChatEngine
            height = '100vh'
            userName='snmm'
			userSecret='fac21snmm'
			projectID='0b24b3f2-2e72-465e-9425-f580985601a6'
		/>

          
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
